[package]

name = "mudpie"
version = "0.0.2"
authors = ["kjp"]
description = "HTTP Application Server for Rust (Alpha)"
repository = "https://github.com/kjpgit/mudpie"
readme = "README.adoc"
license = "Unlicense"
