[package]

name = "mudpie"
version = "0.0.6"
authors = ["kjp"]
description = "HTTP Application Server, inspired by WSGI.  Pure safe Rust, no dependencies."
repository = "https://github.com/kjpgit/mudpie"
readme = "README.adoc"
license = "Unlicense"
